spark:
  app:
    name: test
  master: local[*]



spring:
  data:
    cassandra:
      keyspace: twitter
      contactPoints: localhost
      schemaAction: CREATE_IF_NOT_EXISTS
      port: 9042
      table: tweet

twitter:
  api:
    consumer:
      key: 99WuRvLr5zId2wBILmTbyatnF
      secret: WPTWO8VoY1KsXMMc0zoJTXsOoMWAhziqHq9R7ngQcoCC2kaNR3
  access:
    token: 91426639-TmDAYfJ8xp2pB2PI5e5kHW40dLRpBXmFfBACU7MwG
    secret: qHeseHlkNxu8AC6tJeCG3lFTx2Cukc4bmgGRTmsC0Ig7v
    level: Read and write




